# Generated by Django 4.1.2 on 2022-12-28 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grupuri.Models.schedule
import grupuri.Models.singletimeevent
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='An',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(default='', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cladire', models.CharField(default='Invalid Building...', max_length=3)),
                ('num', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week', models.IntegerField(default=grupuri.Models.schedule.Week['ERR'])),
                ('day', models.IntegerField(default=grupuri.Models.schedule.Day['ERR'])),
                ('startingHour', models.IntegerField(default=0)),
                ('sala', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='grupuri.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Semigrupa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
                ('nume', models.CharField(default='', max_length=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('grupa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='semigrupe', to='grupuri.grupa')),
            ],
        ),
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('materie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grupuri.materie')),
                ('profesor', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursuri', to='grupuri.profesor')),
            ],
            bases=('grupuri.materie',),
        ),
        migrations.CreateModel(
            name='Laborator',
            fields=[
                ('materie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grupuri.materie')),
                ('asistent', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratoare', to='grupuri.profesor')),
                ('semigrupa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='laboratoare', to='grupuri.semigrupa')),
            ],
            bases=('grupuri.materie',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('semigrupa', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='studenti', to='grupuri.semigrupa')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=0)),
                ('nume', models.CharField(default='', max_length=5)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('an', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='serii', to='grupuri.an')),
            ],
        ),
        migrations.AddField(
            model_name='grupa',
            name='serie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='grupe', to='grupuri.serie'),
        ),
        migrations.CreateModel(
            name='CustomInclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupuri.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_inclusions', to='grupuri.student')),
            ],
        ),
        migrations.CreateModel(
            name='CustomExclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupuri.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exclusions', to='grupuri.student')),
            ],
        ),
        migrations.AddField(
            model_name='an',
            name='facultate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ani', to='grupuri.facultate'),
        ),
        migrations.CreateModel(
            name='SingleTimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Invalid title', max_length=100)),
                ('description', models.TextField(blank=True, default='Invalid description', null=True)),
                ('due_date', models.DateTimeField(default=grupuri.Models.singletimeevent.one_week_view)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grupuri.curs')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('materie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grupuri.materie')),
                ('grupa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seminare', to='grupuri.grupa')),
                ('seminarist', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminare', to='grupuri.profesor')),
            ],
            bases=('grupuri.materie',),
        ),
        migrations.CreateModel(
            name='ScheduleS',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grupuri.schedule')),
                ('seminar', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='grupuri.seminar')),
            ],
            bases=('grupuri.schedule',),
        ),
        migrations.CreateModel(
            name='ScheduleL',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grupuri.schedule')),
                ('laborator', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='grupuri.laborator')),
            ],
            bases=('grupuri.schedule',),
        ),
        migrations.CreateModel(
            name='ScheduleC',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grupuri.schedule')),
                ('curs', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='grupuri.curs')),
            ],
            bases=('grupuri.schedule',),
        ),
        migrations.AddField(
            model_name='curs',
            name='serie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cursuri', to='grupuri.serie'),
        ),
    ]
