# Generated by Django 4.1.2 on 2022-12-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupuri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semigrupa',
            name='num',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='num',
        ),
    ]
