# Generated by Django 4.1.2 on 2022-12-29 10:50

from django.db import migrations, models
import django.db.models.deletion
import grupuri.Models.singletimeevent
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grupuri', '0002_remove_semigrupa_num_remove_serie_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Invalid title', max_length=100)),
                ('description', models.TextField(blank=True, default='Invalid description', null=True)),
                ('tip', models.CharField(default='examen', max_length=20)),
                ('date', models.DateTimeField(default=grupuri.Models.singletimeevent.one_week_view)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('curs', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='examene', to='grupuri.curs')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mesaj', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificari', to='grupuri.materie')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Invalid title', max_length=100)),
                ('description', models.TextField(blank=True, default='Invalid description', null=True)),
                ('due_date', models.DateTimeField(default=grupuri.Models.singletimeevent.one_week_view)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('curs', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='teme', to='grupuri.curs')),
            ],
        ),
        migrations.DeleteModel(
            name='SingleTimeEvent',
        ),
    ]
