# Generated by Django 4.1.2 on 2022-12-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupuri', '0003_examen_notificationschedule_tema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationschedule',
            name='sender',
        ),
        migrations.CreateModel(
            name='NotificationSeminar',
            fields=[
                ('notificationschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grupuri.notificationschedule')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificari', to='grupuri.seminar')),
            ],
            bases=('grupuri.notificationschedule',),
        ),
        migrations.CreateModel(
            name='NotificationLab',
            fields=[
                ('notificationschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grupuri.notificationschedule')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificari', to='grupuri.laborator')),
            ],
            bases=('grupuri.notificationschedule',),
        ),
        migrations.CreateModel(
            name='NotificationCourse',
            fields=[
                ('notificationschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grupuri.notificationschedule')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificari', to='grupuri.curs')),
            ],
            bases=('grupuri.notificationschedule',),
        ),
    ]
